
var firstnamesArray =["JUAN","JOSÉ LUIS","JOSÉ","MARÍA GUADALUPE","FRANCISCO","GUADALUPE","JUANA","ANTONIO","JESÚS","MIGUEL ÁNGEL","PEDRO","MANUEL","MARGARITA","MARÍA DEL CARMEN","JUAN CARLOS","ROBERTO","FERNANDO","DANIEL","CARLOS","JORGE","RICARDO","MIGUEL","EDUARDO","JAVIER","RAFAEL","MARTÍN","RAÚL","DAVID","JOSEFINA","JOSÉ ANTONIO","ARTURO","MARCO ANTONIO","JOSÉ MANUEL","FRANCISCO JAVIER","ENRIQUE","VERÓNICA","GERARDO","MARÍA ELENA","LETICIA","ROSA","MARIO","FRANCISCA","ALFREDO","TERESA","ALICIA","MARÍA FERNANDA","SERGIO","ALBERTO","LUIS","ARMANDO","ALEJANDRA","MARTHA","SANTIAGO","YOLANDA","PATRICIA","MARÍA DE LOS ÁNGELES","JUAN MANUEL","ROSA MARÍA","ELIZABETH","GLORIA","ÁNGEL","GABRIELA","SALVADOR","VÍCTOR MANUEL","SILVIA","MARÍA DE GUADALUPE","MARÍA DE JESÚS","GABRIEL","ANDRÉS","ÓSCAR","GUILLERMO","ANA MARÍA","RAMÓN","MARÍA ISABEL","PABLO","RUBEN","ANTONIA","MARÍA LUISA","LUIS ÁNGEL","MARÍA DEL ROSARIO","FELIPE","JORGE JESÚS","JAIME","JOSÉ GUADALUPE","JULIO CESAR","JOSÉ DE JESÚS","DIEGO","ARACELI","ANDREA","ISABEL","MARÍA TERESA","IRMA","CARMEN","LUCÍA","ADRIANA","AGUSTÍN","MARÍA DE LA LUZ","GUSTAVO"];
var lastnamesArray = ["AARON","ABDIAS","ABDIES","ABDO","ABDON","ABEL","ABELARD","ABELARDO","ABELIN","ABILI","ABILIO","ABILLI","ABRAHAM","ABUNDI","ABUNDIO","ACAB","ACISCLE","ACISCLO","ADALBERT","ADALBERTO","ADAM","ADAN","ADELARD","ADELARDO","ADEMAR","ADIRAN","ADOLBA","ADOLF","ADOLFO", "ADRIA"];
var fullnamesArray = [];
var i = 0;

for(var j = 0; j < firstnamesArray.length; j++){
    for(var k = 0; k < lastnamesArray.length; k++) {
        fullnamesArray[i] = firstnamesArray[j] + " " + lastnamesArray[k];
        i++; } }

for(var i = 0; i < fullnamesArray.length; i++){
    console.log(fullnamesArray[i]); }
